---
title: School District Secession in East Baton Rouge
authors:
  - name: Caitlin Moroney
    department: Department of Mathematics & Statistics
    affiliation: American University
    location: Washington, DC
    email: cm0246b@american.edu
abstract: |
  Enter the text of your abstract here.
keywords:
  - education
  - race
  - schools
  - school district secession
  - school district fragmentation
bibliography: references.bib
output: 
  rticles::arxiv_article:
    keep_tex: true
---

# Proposal

I am interested in examining the relationships between school performance, race, and socioeconomic indicators (including income and percentage of "economically disadvantaged"[^I use the Louisiana Department of Education’s data on percentages of economically disadvantaged students. I have yet to find sufficient metadata explaining how they define "economically disadvantaged," but comparing current school and school district performance reports with past reports suggests that this may be the percentage of students on free or reduced lunch plans.] students). Furthermore, I am interested in examining this data within the context of school district "secession."^[See CITATION HERE for a thorough explanation of the school district "secession" phenomenon.] I have chosen to focus on schools within East Baton Rouge Parish, Louisiana for two reasons: (1) there are stark differences among school districts with regard to school and school district performance [CITATION HERE], and (2) residents in the southeast corner of the Parish recently voted to incorporate as the City of St. George with the intention of forming a new school district [CITATION HERE]. If successful in creating a new school district, St. George will be the fourth new district to “secede” from the original East Baton Rouge Parish School District in two decades.

I propose to investigate the following research questions:

* Is there evidence that suggests the clustering of racial groups in East Baton Rouge (EBR) Parish?
* Is there evidence of the clustering of income levels in EBR Parish?
* Is there evidence of racial stratification of income?
* Is there evidence to suggest that school performance is linked to the racial makeup of the student body, the percentage of economically disadvantaged students, and/or the percentage of students fully proficient in English?

# Abstract
\label{sec:abstract}


# Introduction



# Methods
\label{sec:methods}


# Results
\label{sec:results}


# Discussion



# Citations
